### ISSUE TITLE
Julia random number generator changed

### ISSUE THREAD

**Issue by tjdiamandis** [cvxgrp/cvxbook_additional_exercises#2]
Many of the Julia data files were generated pre-1.7. In version 1.7, the default random number generator was changed, so starting with the same seed does not yield the same values post vs. pre-1.7. When I submit updates to the Julia data files, should I use the old (`MersenneTwister`) or the new default (`Xoshiro256++`)?

Language update:
https://docs.julialang.org/en/v1.7-dev/NEWS/#Language-changes

Also documented in the top of the `Random` stdlib docs
https://docs.julialang.org/en/v1/stdlib/Random/

**Comment by PTNobel** [comment]
Hmmm, my soft preference is to switch to the new RNG but I can check with Stephen on Monday to get you a hard answer.

**Comment by tjdiamandis** [comment]
I also think that makes more sense (but it will require changing the solutions).

**Comment by stephenpboyd** [comment]
I’d use the new default.  No problem if we get somewhat different solutions, numbers, etc.

Theo, it’s great you’re doing this.  It will be very good to have the problem, data, and solutions codes in Julia more up to date.

If you like, we can give you access (if you don’t already have it) to edit the additional exercises .tex files.  Then you could not only update the problem and solution codes, but also the .tex files, eg, where a number has changed.

**Comment by tjdiamandis** [comment]
That sounds great. I don't currently have access. 

I'm happy to update the code & .tex files for the problems (but no promises on timeline).

**Comment by PTNobel** [comment]
I'll add you now to that repo @tjdiamandis

**Comment by tjdiamandis** [comment]
Closing since question was resolved
